### ISSUE TITLE
Not working with .Net 5

### ISSUE THREAD

**Issue by theumairtahir** [KishorNaik/Sol_OData_Swagger_Support#1]
I have followed the steps you mentioned and tried some other solutions but it is giving the same error.
I am using ASP.NET 5.0 WebAPI

**Comment by KishorNaik** [comment]
@ut786 :
Case 1:
I migrated the solution from 3.1 to 5.0 but still the solution worked at my end. I just change the framework.
```xml
<PropertyGroup>
       <TargetFramework>net5.0</TargetFramework>
</PropertyGroup>
```
The swagger ui is perfectly working well. 

Case 2:
I created a new Asp.Net 5.0 web api solution and followed the same step which I mentioned in the Readme.md file. The swagger ui is perfectly working well.
Please check the following packages are installed or not in your solution.
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" NoWarn="NU1605" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" NoWarn="NU1605" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.5.2" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
		<PackageReference Include="OData.Swagger" Version="1.0.0" />
	</ItemGroup>
</Project>
```

For your reference, Please check the following Asp.net Web Api 5.0 solution file.
[5.0 Solution](https://github.com/KishorNaik/Sol_OData_Swagger_Support/tree/master/V5.0/Sol_Demo/Api)

**Comment by theumairtahir** [comment]
Still not working at my end. Can you please check my [project](https://github.com/ut786/Dapper.OData.git)

**Comment by KishorNaik** [comment]
@ut786 
 You are using following version of OData Library. Maybe some api's is deprecated in this version.
 ```javascript
<PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.0-preview2" />
```
I am using Stable version.
 ```javascript
<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.5.2" />
```

**Comment by theumairtahir** [comment]
Issue fixed by degrading the OData version as you mentioned. thanks!

**Comment by KishorNaik** [comment]
Most Welcome.
