### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gordon-matt** [KishorNaik/Sol_OData_Swagger_Support#2]
I have followed the instructions, but can't get this to work. I am using .NET 5. I did see issue: #1 . However, it's not relevant to me, as I am using the same stable version of OData (7.5.2). I think it may have something to do with my unique way of registering OData routes. Could you have a look see for me? Here's the project: [BlazorEmployeeManagementTutorial](https://github.com/gordon-matt/BlazorEmployeeManagementTutorial).

The above project makes use of another project of mine: [Extenso.AspNetCore.OData](https://github.com/gordon-matt/Extenso/tree/master/Extenso.AspNetCore.OData). I hope you can help. Thanks

**Comment by KishorNaik** [comment]
@gordon-matt:
Your swagger UI is working perfectly fine but api specification does not display in the Swagger UI page. It means swagger doc is not able to read your api points because of OData routes which you had created.(Extenso.AspNetCore.OData)

I created a demo api controller in the controller folder and it displays the api specification in the swagger Ui page. It is working perfectly fine. You have to check your library for the cause.

**Comment by gordon-matt** [comment]
Thanks for your response, but maybe there is some misunderstanding here. I just had a look at your demo and neither of the 2 controllers you have inherit from `Microsoft.AspNet.OData.ODataController`. I assumed your code would generate swagger documentation for `ODataControllers`. Was I mistaken? I am a little confused now.

**Comment by KishorNaik** [comment]
@gordon-matt :

I had created an Api Controller in the Controller folder and inherit from ODataController class. Add the following notation in the controller section.

```C#
[ApiExplorerSettings(IgnoreApi = false)] 
```
Note: without notation it will not display api specification in swagger UI page. 

Full Api Controller Code.
```C#
using Microsoft.AspNet.OData;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagement.Api.Controllers
{
    [ApiExplorerSettings(IgnoreApi = false)]
    [Route("api/demo")]
    [ApiController]
    public class DemoODataController : ODataController
    {
        [HttpGet("get")]
        public IActionResult DemoGet()
        {
            return base.Ok("Ok");
        }
    }
}
```

Voila, Now we can view the api specification on swagger Ui page.

**Comment by gordon-matt** [comment]
Thanks, but I get an error as follows:

`Only actions which use attribute routing support ApiExplorer`

I guess this means conventional routing is not supported. That would be a problem for me then, as I use a Generic OData Controller to make life easier.. and inherit from that in 90%+ of my ODataControllers..

**Comment by KishorNaik** [comment]
@gordon-matt :
Yes you are right. 
You can only apply the ```[ApiExplorerSettings]``` attribute to controllers and actions that use attribute routing. If you enable the ApiExplorer on an action that uses conventional routing, you will be greeted with an error like the following:

```Only actions which use attribute routing support ApiExplorer```
